### ISSUE TITLE
server side codes

### ISSUE THREAD

**Issue by jason-shen** [skyrocketscommunity/React-native-webrtcApp#1]
would be nice if you can share the signal side as well

cheers

**Comment by de-saksham** [comment]
The endpoint at the frontend is not connecting. Would be great if you could provide the backend code or at least tell us how the signaling is working. Thanks.

**Comment by Anas-MI** [comment]
Would love to see the backend code for this

**Comment by MadCoderme** [comment]
Please share the backend code, it will help a lot

**Comment by de-saksham** [comment]
> would be nice if you can share the signal side as well
> 
> cheers

Did you get the backend code?

**Comment by jason-shen** [comment]
> > would be nice if you can share the signal side as well
> > cheers
> 
> Did you get the backend code?

don't bother mate, i don't think the author is gonna do it, i wrote my own

**Comment by de-saksham** [comment]
> > > would be nice if you can share the signal side as well
> > > cheers
> > 
> > 
> > Did you get the backend code?
> 
> don't bother mate, i don't think the author is gonna do it, i wrote my own

That's the true spirit, I am also working on my own. 
Thank you for the quick reply.

**Comment by jason-shen** [comment]
> > > > would be nice if you can share the signal side as well
> > > > cheers
> > > 
> > > 
> > > Did you get the backend code?
> > 
> > 
> > don't bother mate, i don't think the author is gonna do it, i wrote my own
> 
> That's the true spirit, I am also working on my own.
> Thank you for the quick reply.

no worries mate, i think the author is more of show off his stuff rather than helping others, let me know if you need help its not hard

**Comment by MadCoderme** [comment]
I also wrote my own using web sockets. And also building my own webrtc script :))

**Comment by de-saksham** [comment]
> > > > > would be nice if you can share the signal side as well
> > > > > cheers
> > > > 
> > > > 
> > > > Did you get the backend code?
> > > 
> > > 
> > > don't bother mate, i don't think the author is gonna do it, i wrote my own
> > 
> > 
> > That's the true spirit, I am also working on my own.
> > Thank you for the quick reply.
> 
> no worries mate, i think the author is more of show off his stuff rather than helping others, let me know if you need help its not hard

exactly, I tried reaching them out via email but no response. 
would be great if you can give me a rough idea about the working.

**Comment by jason-shen** [comment]
> > > > > > would be nice if you can share the signal side as well
> > > > > > cheers
> > > > > 
> > > > > 
> > > > > Did you get the backend code?
> > > > 
> > > > 
> > > > don't bother mate, i don't think the author is gonna do it, i wrote my own
> > > 
> > > 
> > > That's the true spirit, I am also working on my own.
> > > Thank you for the quick reply.
> > 
> > 
> > no worries mate, i think the author is more of show off his stuff rather than helping others, let me know if you need help its not hard
> 
> exactly, I tried reaching them out via email but no response.
> would be great if you can give me a rough idea about the working.

yeah you will find his codes are not 100% correct but its a good start

**Comment by jason-shen** [comment]
> > > > > > would be nice if you can share the signal side as well
> > > > > > cheers
> > > > > 
> > > > > 
> > > > > Did you get the backend code?
> > > > 
> > > > 
> > > > don't bother mate, i don't think the author is gonna do it, i wrote my own
> > > 
> > > 
> > > That's the true spirit, I am also working on my own.
> > > Thank you for the quick reply.
> > 
> > 
> > no worries mate, i think the author is more of show off his stuff rather than helping others, let me know if you need help its not hard
> 
> exactly, I tried reaching them out via email but no response.
> would be great if you can give me a rough idea about the working.

give me your email

**Comment by de-saksham** [comment]
> > > > > > > would be nice if you can share the signal side as well
> > > > > > > cheers
> > > > > > 
> > > > > > 
> > > > > > Did you get the backend code?
> > > > > 
> > > > > 
> > > > > don't bother mate, i don't think the author is gonna do it, i wrote my own
> > > > 
> > > > 
> > > > That's the true spirit, I am also working on my own.
> > > > Thank you for the quick reply.
> > > 
> > > 
> > > no worries mate, i think the author is more of show off his stuff rather than helping others, let me know if you need help its not hard
> > 
> > 
> > exactly, I tried reaching them out via email but no response.
> > would be great if you can give me a rough idea about the working.
> 
> give me your email

saksham.bhatnagar@hotmail.com

**Comment by de-saksham** [comment]
You all can download the backend file which I have coded from here: 
https://drive.google.com/file/d/1efCEoM6N5qZSYMi--BO0a-vGaOVYeJFs/view?usp=sharing

**Comment by Anas-MI** [comment]
It would be great if you can share the details with me too.
anas3rde@gmail.com.

Thanks a ton!

**Comment by Anas-MI** [comment]
Oh lovely.Thanks!!!

**Comment by Anas-MI** [comment]
Btw

Does this work properly along with reactnative app? or should we have to
make further changes?

**Comment by Anas-MI** [comment]
Btw

Does this work properly along with reactnative app? or should we have to
make further changes?

**Comment by jason-shen** [comment]
use socket.io is a better idea, as socket.io has build in ping pong, so it will keep you connected, if you use the standard socket, you will have to implement the reconnection your self.
